apiVersion: project.chelala.one/v1alpha1
kind: Project
metadata:
  labels:
    testing.upbound.io/example-name: example
  annotations:
    crossplane.io/external-name: "Solicitud Cliente Crédito"
  name: solicitud-cliente-credito
spec:
  managementPolicies:
    - Observe
  deletionPolicy: Orphan
  forProvider:
    name: "Solicitud Cliente Crédito"
---
apiVersion: gitrepository.chelala.one/v1alpha1
kind: Repository
metadata:
  annotations:
    crossplane.io/external-name: "Solicitud Cliente Crédito/solcliente-web"
  labels:
    testing.upbound.io/example-name: example
  name: solcliente-web
spec:
  managementPolicies:
    - Observe
  deletionPolicy: Orphan
  forProvider:
    initialization:
      - initType: Uninitialized
    name: "Solicitud Cliente Crédito/solcliente-web"
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
---
apiVersion: gitrepositorybranch.chelala.one/v1alpha1
kind: RepositoryBranch
metadata:
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    name: example
    refBranch: develop
    repositoryIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example



