/*
Copyright 2022 Upbound Inc.
*/
// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	v1alpha1 "github.com/chelala/provider-azuredevops/apis/gitrepository/v1alpha1"
	reference "github.com/crossplane/crossplane-runtime/pkg/reference"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this RepositoryBranch.
func (mg *RepositoryBranch) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.RefBranch),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.RefBranchRef,
		Selector:     mg.Spec.ForProvider.RefBranchSelector,
		To: reference.To{
			List:    &RepositoryBranchList{},
			Managed: &RepositoryBranch{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.RefBranch")
	}
	mg.Spec.ForProvider.RefBranch = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.RefBranchRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.RepositoryID),
		Extract:      v1alpha1.ExtractResourceID(),
		Reference:    mg.Spec.ForProvider.RepositoryIDRef,
		Selector:     mg.Spec.ForProvider.RepositoryIDSelector,
		To: reference.To{
			List:    &v1alpha1.RepositoryList{},
			Managed: &v1alpha1.Repository{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.RepositoryID")
	}
	mg.Spec.ForProvider.RepositoryID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.RepositoryIDRef = rsp.ResolvedReference

	return nil
}
