apiVersion: gitrepositorybranch.chelala.one/v1alpha1
kind: RepositoryBranch
metadata:
  annotations:
    meta.upbound.io/example-id: gitrepositorybranch/v1alpha1/repositorybranch
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    name: example-branch-name
    refBranchSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    repositoryIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: gitrepository.chelala.one/v1alpha1
kind: Repository
metadata:
  annotations:
    meta.upbound.io/example-id: gitrepositorybranch/v1alpha1/repositorybranch
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    initialization:
    - initType: Clean
    name: Example Git Repository
    projectIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example

---

apiVersion: project.chelala.one/v1alpha1
kind: Project
metadata:
  annotations:
    meta.upbound.io/example-id: gitrepositorybranch/v1alpha1/repositorybranch
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    name: Example Project
    versionControl: Git
    visibility: private
    workItemTemplate: Agile
